### ISSUE TITLE
The Connected users are not updated in the User List

### ISSUE THREAD

**Issue by mokarrom20** [GodotNuts/FirebaseDemo-SociaDot#1]
![image](https://user-images.githubusercontent.com/79036724/109770851-5022ee00-7c26-11eb-8681-771ddcd9a5e7.png)
As you can see , i connected someone but "the one" is not seem to be connected in the user list ☺
Hope this issue will be resolved

**Comment by fenix-hub** [comment]
Thanks! If you find any other bug feel free to open new issues :)
