### ISSUE TITLE
Spelling mistake [bug or feature?]

### ISSUE THREAD

**Issue by mokarrom20** [GodotNuts/FirebaseDemo-SociaDot#15]
when you want to write something in Sociadot i found out that the "add image" was "add immage" [might be intentional]
**i am using version 1.1**
![image](https://user-images.githubusercontent.com/79036724/130350194-73d3888f-432d-4b07-986c-6c74d0c564fd.png)

**Comment by fenix-hub** [comment]
Hi @mokarrom20 ,
This feature™ was fixed in the recent version of the client. You can download it here [v1.5](https://github.com/GodotNuts/FirebaseDemo-SociaDot/releases/tag/v1.5)
